server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    slave-list:
      - name: slave_1
        url: jdbc:mysql://localhost:3307/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
      #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #generate-ddl: false
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        #enable_lazy_load_no_trans: true
        format_sql: true
    #open-in-view: false
  profiles:
    include: jwt

